---

# Add letsencrypt certificates to `install_files` .
- block:
    - name: Define local cert source pathes
      set_fact:
        # By using incorrect mode for certificate files here i may trigger
        # `restart` handler for corresponding service in later roles.
        install_letsencrypt_certs: >
          {{ install_letsencrypt_certs +
            [ { 'src' : local_cert_dir + item.letsencrypt_name + cert_fullchain_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.fullchain | default({}), recursive=True)
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_cert_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.cert | default({}), recursive=True)
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_privkey_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.privkey | default({}), recursive=True)
            ] | selectattr('dest', 'defined') | list
          }}
      when: item.letsencrypt_name is defined
      loop: "{{ install_certs }}"

    - name: Stat local cert source files
      local_action:
        module: stat
        path: "{{ item.src }}"
      register: install_letsencrypt_certs_stats
      loop: "{{ install_letsencrypt_certs }}"

    - name: Add letsencrypt certs to install files
      set_fact:
        install_files: "{{ install_files + [item.item] }}"
      when: item.stat.exists
      loop: "{{ install_letsencrypt_certs_stats.results }}"
    - name: Gather missed letsencrypt certs
      set_fact:
        missed_install_files: "{{ missed_install_files + [item.item] }}"
      when: not item.stat.exists
      loop: "{{ install_letsencrypt_certs_stats.results }}"

    - name: Show install_files
      debug:
        var: install_files
    - name: Show MISSED install files
      debug:
        var: missed_install_files

    - name: MISSED install files found, wait a moment (10s)
      wait_for:
        timeout: 10
      when: missed_install_files | length > 0
  tags:
    - 'debug'

