---

# Add letsencrypt certificates to `install_files` .
- block:
    - name: Define local source cert pathes
      set_fact:
        # By using incorrect mode for certificate files here i may trigger
        # `restart` handler for corresponding service in later roles.
        install_letsencrypt_certs: >
          {{ install_letsencrypt_certs | default([]) +
            [ { 'src' : local_cert_dir + item.letsencrypt_name + cert_fullchain_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.fullchain | default({}), recursive=True)
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_cert_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.cert | default({}), recursive=True)
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_privkey_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.privkey, recursive=True)
            ] | selectattr('dest', 'defined') | list
          }}
      when: item.letsencrypt_name is defined
      loop: "{{ install_certs }}"
    - name: debug
      debug:
        var: install_letsencrypt_certs
    - name: Stat source files
      local_action:
        module: stat
        path: "{{ item.src }}"
      register: install_letsencrypt_certs_stats
      loop: "{{ install_letsencrypt_certs }}"
    - name: debug
      debug:
        var: install_letsencrypt_certs_stats
    - name: Add letsencrypt certs to install files
      set_fact:
        install_files: "{{ install_files | default([]) + [item.item] }}"
      when: item.stat.exists
      loop: "{{ install_letsencrypt_certs_stats.results }}"
    - name: Debug install_files
      debug:
        var: install_files
  tags:
    - 'debug'

