---

- block:
    - name: Define nginx share roots
      set_fact:
        _nginx_share_roots: >-
          {{ dict(ks | zip(vs)) }}
      vars:
        ks: >-
          {{ _nginx_host_shares
                | selectattr('vhost', 'defined')
                | map(attribute='vhost')
                | list
          }}
        vs: >-
          {{ _nginx_host_shares
                | selectattr('vhost', 'defined')
                | list
          }}
      when: _nginx_host_shares is defined

    - name: Show nginx share roots dict
      debug:
        var: _nginx_share_roots

    - name: install | Define certificates installed to share
      set_fact:
        letsencrypt_install_shared: >-
          {{ letsencrypt_install_shared +
            [ { 'src' : local_cert_dir + item.letsencrypt_name + cert_fullchain_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              , 'dest' : _nginx_share_roots[item.fullchain.share].root
                            + '/' + item.letsencrypt_name + '/' + cert_fullchain_fn
              , 'server' : _nginx_share_roots[item.fullchain.share].server
              } | combine(item.fullchain)
              if item.fullchain is defined and item.fullchain.share is defined else {}
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_chain_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              , 'dest' : _nginx_share_roots[item.chain.share].root
                            + '/' + item.letsencrypt_name + '/' + cert_chain_fn
              , 'server' : _nginx_share_roots[item.chain.share].server
              } | combine(item.chain)
              if item.chain is defined and item.chain.share is defined else {}
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_cert_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              , 'dest' : _nginx_share_roots[item.cert.share].root
                            + '/' + item.letsencrypt_name + '/' + cert_cert_fn
              , 'server' : _nginx_share_roots[item.cert.share].server
              } | combine(item.cert)
              if item.cert is defined and item.cert.share is defined else {}
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_privkey_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              , 'dest' : _nginx_share_roots[item.privkey.share].root
                            + '/' + item.letsencrypt_name + '/' + cert_privkey_fn
              , 'server' : _nginx_share_roots[item.privkey.share].server
              } | combine(item.privkey)
              if item.privkey is defined and item.privkey.share is defined else {}
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_pfx_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              , 'dest' : _nginx_share_roots[item.pfx.share].root
                            + '/' + item.letsencrypt_name + '/' + cert_pfx_fn
              , 'server' : _nginx_share_roots[item.pfx.share].server
              } | combine(item.pfx)
              if item.pfx is defined and item.pfx.share is defined else {}
            ] | selectattr('dest', 'defined') | list
          }}
      vars:
      when: item.letsencrypt_name is defined
      loop: "{{ install_certs }}"

    - name: install | Show certs install to share
      debug:
        var: letsencrypt_install_shared

# Add letsencrypt certificates to `install_files` .
- block:
    - name: install | Define local cert source pathes
      set_fact:
        letsencrypt_install: >-
          {{ letsencrypt_install +
            [ { 'src' : local_cert_dir + item.letsencrypt_name + cert_fullchain_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.fullchain | default({}))
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_chain_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.chain | default({}))
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_cert_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.cert | default({}))
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_privkey_fn
              , 'mode': 600
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.privkey | default({}))
            , { 'src' : local_cert_dir + item.letsencrypt_name + cert_pfx_fn
              , 'mode': 644
              , 'letsencrypt_name' : item.letsencrypt_name
              } | combine(item.pfx | default({}))
            ] | selectattr('dest', 'defined') | list
          }}
      vars:
      when: item.letsencrypt_name is defined
      loop: "{{ install_certs }}"

    - name: install | Stat local cert source files
      local_action:
        module: stat
        path: "{{ item.src }}"
      register: letsencrypt_install_src_stats
      loop: "{{ letsencrypt_install }}"

    - name: install | Stat remote cert dest files
      stat:
        path: "{{ item.dest }}"
      register: letsencrypt_install_dest_stats
      loop: "{{ letsencrypt_install }}"

    - name: install | Define new letsencrypt certificates to install
      set_fact:
        new_installed_certs: "{{ new_installed_certs + [item.0.item] }}"
      when: item.0.stat.exists and not item.1.stat.exists
      loop: >
        {{ letsencrypt_install_src_stats.results
            | zip(letsencrypt_install_dest_stats.results)
            | list
        }}

    - name: install | Define existing letsencrypt certificates to update
      set_fact:
        update_installed_certs: "{{ update_installed_certs | default([]) + [item.0.item] }}"
      when: item.0.stat.exists and item.1.stat.exists
      loop: >
        {{ letsencrypt_install_src_stats.results
            | zip(letsencrypt_install_dest_stats.results)
            | list
        }}

    - name: install | Define missed install certificate files
      set_fact:
        missed_installed_certs: "{{ missed_installed_certs + [item.item] }}"
      when: not item.stat.exists
      loop: "{{ letsencrypt_install_src_stats.results }}"

    - name: install | Show new certs to install
      debug:
        var: new_installed_certs

    - name: install | Show certs to update
      debug:
        var: update_installed_certs

    - name: install | Show MISSED install certificate files
      debug:
        var: missed_installed_certs

    - name: install | MISSED install files found, wait a moment (10s)
      wait_for:
        timeout: 10
      when: missed_installed_certs | length > 0

  tags:
    - 'debug'

# Install or update certificate files.
- block:
    - name: install (nginx_host) | Create directories on share
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
        force: no
      loop: "{{ letsencrypt_install_shared }}"
      delegate_to: "{{ item.server }}"

    - name: install (nginx_host) | Install certificates to share
      copy:
        src:  "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        force: no
      loop: "{{ letsencrypt_install_shared }}"
      delegate_to: "{{ item.server }}"

- block:
    - name: install | Install new letsencrypt certificates
      copy:
        src:  "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        force: no
      loop: "{{ new_installed_certs }}"
      register: certs_installed
    # I should not change mode for existing certificates, because this may
    # cause loop of `changed` status: this task will set some mode, but later
    # task (e.g. for service using that certificate) will reset mode to some
    # other value. Then on next playbook run this will happen again and again.
    - name: install | Update existing letsencrypt certificates
      copy:
        src:  "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ update_installed_certs }}"
      register: certs_updated
  tags:
    - 'debug'

