
# Obtain local cert db stats.
- block:
    - name: Create local cert db directory
      file:
        path: "{{ local_cert_dir }}"
        state: directory
    - name: Stat certificate files in local cert db
      stat:
        path: "{{ item.local_files.cert }}"
      register: transfer_certs_cert_stats
      loop: "{{ letsencrypt_files }}"
    - name: Stat created_by files in local cert db
      stat:
        path: "{{ item.local_files.created_by }}"
      register: transfer_certs_created_stats
      loop: "{{ letsencrypt_files }}"
  delegate_to: localhost

# Define local cert db variables.
- block:
    - name: Define new certificates
      set_fact:
        new_certs: "{{ new_certs + [item.item] }}"
      when: not item.stat.exists
      loop: "{{ transfer_certs_cert_stats.results }}"

    - name: Define orphaned certificates
      set_fact:
        orphaned_certs: "{{ orphaned_certs + [item.0.item] }}"
      when: item.0.stat.exists and not item.1.stat.exists
      loop: >
        {{ transfer_certs_cert_stats.results
            | zip(transfer_certs_created_stats.results)
            | list
        }}

    # E.g. orphaned certificates may be counted here too (because `when` check
    # is not sufficient), but this does not matter..
    - name: Define mismatched certificates
      set_fact:
        mismatched_certs: "{{ mismatched_certs + [item.item] }}"
      when: item.stat.exists and ansible_hostname != lookup('file', item.item.local_files.created_by)
      loop: "{{ transfer_certs_created_stats.results }}"

    - name: Define matched certificates
      set_fact:
        matched_certs: "{{ matched_certs + [item.item] }}"
      when: item.stat.exists and ansible_hostname == lookup('file', item.item.local_files.created_by)
      loop: "{{ transfer_certs_created_stats.results }}"

    - name: Show new certificates
      debug:
        var: new_certs
    - name: Show matched certificates
      debug:
        var: matched_certs

    - name: Show transfer certs
      debug:
        var: transfer_certs

    - name: Show orphaned certificates
      debug:
        var: orphaned_certs
    - name: Show mismatched certificates
      debug:
        var: mismatched_certs

    - name: MISMATCHED or ORPHANED cert files found, wait a moment (10s)
      wait_for:
        timeout: 10
      when: mismatched_certs | length > 0 or orphaned_certs | length > 0

