---

# To use this, i need to enable ddns updates on Powerdns server. For this:
#
# 1. Generate tsig key
#
#     pdnsutil generate-tsig-key key-name hmac-sha512
#
# the key will be already added to `tsigkeys` table.
#
# 2. Allow updates for zone with specified key name:
#
#     insert into domainmetadata (domain_id , kind , content ) values (X, 'TSIG-ALLOW-DNSUPDATE', 'key-name');
#
# where X is `domain_id` from `domains` table and `key-name` is key name.
#
# 3. Allow ddns updates for zone from external server IP:
#
#     insert into domainmetadata (domain_id , kind , content ) values (1, 'ALLOW-DNSUPDATE-FROM', 'IP/32');
#
# where IP is external server IP.
#
# 4. Made content of tsig key available for ansible (e.g. copy to local file on
# ansible master).
#
# During play run acme challange in saved in `acme_challenge.txt`, so
# subsequent runs will use previous acme challenge. But if you want to obtain
# new challenge, delete this file _manually_.
#
# I may force reissuing of certificate (earlier, than its expiration) by
# deleting certificate file.

- name: Define variables
  import_tasks: define_vars.yml
  tags:
    - always

- name: Check local certs db
  import_tasks: local_cert_db.yml
  tags:
    - 'letsencrypt'
    - 'letsencrypt_local_db'

- block:
    # Set 'test_ddns=true' to perform ddns test.
    - name: Test ddns
      include_tasks:
        file: test_ddns.yml
        apply:
          tags:
            - test
      when: test_ddns
      tags:
        - test
        - test_ddns_add
        - test_ddns_del
        - test_ddns_notify

    - name: Obtain letsencrypt certificate.
      import_tasks: letsencrypt.yml
  when: letsencrypt_files | length > 0
  tags:
    - 'letsencrypt'

- name: Install letsencrypt certificates from local db
  import_tasks: install_certs.yml
  tags:
    - 'letsencrypt'
    - 'letsencrypt_install'
    - 'ssl'

