---

# To use this, i need to enable ddns updates on Powerdns server. For this:
#
# 1. Generate tsig key
#
#     pdnsutil generate-tsig-key key-name hmac-sha512
#
# the key will be already added to `tsigkeys` table.
#
# 2. Allow updates for zone with specified key name:
#
#     insert into domainmetadata (domain_id , kind , content ) values (X, 'TSIG-ALLOW-DNSUPDATE', 'key-name');
#
# where X is `domain_id` from `domains` table and `key-name` is key name.
#
# 3. Allow ddns updates for zone from external server IP:
#
#     insert into domainmetadata (domain_id , kind , content ) values (1, 'ALLOW-DNSUPDATE-FROM', 'IP/32');
#
# where IP is external server IP.
#
# 4. Made content of tsig key available for ansible (e.g. copy to local file on
# ansible master).
#
# During play run acme challange in saved in `acme_challenge.txt`, so
# subsequent runs will use previous acme challenge. But if you want to obtain
# new challenge, delete this file _manually_.

- name: Check empty list
  fail:
    msg: "Let's encrypt certificate definitions list `letsencrypt_certs` is empty."
  when: letsencrypt_certs is undefined or letsencrypt_certs | length == 0
  tags:
    - 'letsencrypt'

- name: Define variables
  import_tasks: define_vars.yml
  tags:
    - 'letsencrypt'
    - 'debug'

- name: Test ddns
  import_tasks: test_ddns.yml
  when: test_ddns
  tags:
    - 'letsencrypt'

- name: Obtain letsencrypt certificate.
  import_tasks: letsencrypt.yml
  tags:
    - 'letsencrypt'

