---

# Note, that because this is _dynamic_ include, tags assigned to `include`
# task are _not_ inherited by _included_ tasks. So i need to repeat here all
# tags from `include` task..
- block:
    # This is a pre-task for role.
    - name: Install required python modules
      apt:
        name: python-dnspython
        state: present

    - name: Add test RR
      nsupdate:
        key_algorithm:  "{{ item.ddns.key_algo }}"
        key_name:       "{{ item.ddns.key_name }}"
        key_secret:     "{{ item.ddns.key_secret }}"
        server: "{{ item.ddns.server }}"
        zone:   "{{ item.ddns.domain }}"
        #record: "testssl1"
        #zone:   "{{ 'testssl1.' + cert_domain + '.' }}"
        record: "{{ 'testssl1.' + item.ddns.domain + '.' }}"
        type: "TXT"
        ttl: 60
        value: ["hui", "huynya"]
        state: present
      loop: "{{ letsencrypt_sans }}"

    - name: Delete test RR
      nsupdate:
        key_algorithm:  "{{ item.ddns.key_algo }}"
        key_name:       "{{ item.ddns.key_name }}"
        key_secret:     "{{ item.ddns.key_secret }}"
        server: "{{ item.ddns.server }}"
        zone:   "{{ item.ddns.domain }}"
        record: "{{ 'testssl1.' + item.ddns.domain + '.' }}"
        type: "TXT"
        state: absent
      loop: "{{ letsencrypt_sans }}"

    - name: Explicitly notify pdns slaves about test RRs
      command: pdns_control notify "{{ item.ddns.domain }}"
      delegate_to: "{{ item.ddns.server }}"
      with_items: "{{ letsencrypt_sans }}"

  tags:
    - 'test'

